sudo: required
language: rust

cache:
    cargo: true
    directories:
        - $HOME/.local

addons:
    apt:
        packages:
            # packages needed for kcov 
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - binutils-dev
            - libiberty-dev

rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true

before_install:
    - export PATH=$PATH:$HOME/.local/bin
    - ci/install_kcov 34 $HOME/.local

install: cargo build --verbose --all

script: 
    - cargo test --verbose --all
    - cargo testsuite -vv

after_success:
    - ci/check_test_coverage target
